In [18]:
import numpy as np

In [57]:
#EXERCICE1

a = np.array([[11, 21], [31, 41]])  
b=a.tolist()
print (b)

[[11, 21], [31, 41]]


In [52]:
#EXERCICE2

x =np.random.randint(1,4, size=(3,3))
print (x)
trace = np.trace(x)
print(trace)

[[3 1 1]
 [1 3 3]
 [3 3 3]]
9


In [68]:
#EXERCICE3

x = np.array([[0, 10, 20], [20, 30, 40]])
print("Values bigger than 10 =", x[x>10])

Values bigger than 10 = [20 20 30 40]


In [56]:
#EXERCICE4

A =np.array([1,2,3])
B =np.array([4,5,6])
C= x+y
print(C)

[5 7 9]


In [64]:
#EXERCICE5

e =int(input("number of rows:"))
z =int(input("number of columns"))
x =int(input("begin:"))
w =int(input("end:"))
a =np.random.randint(x,w,size=(e,z))
for i in a:
    print(i)
    y=i.mean()
    print("average:",y)
    for j in i:
        v=j-y
        print("v",v)

number of rows:2
number of columns2
begin:2
end:6
[5 3]
average: 4.0
v 1.0
v -1.0
[5 4]
average: 4.5
v 0.5
v -0.5
